name: Run eslint
description: Run eslint on JavaScript files
author: 18F
inputs:
  repo-token:
    description: Token for the GitHub API
    required: true
  path:
    description: Path to be linted
    required: false
    default: ''
  files:
    description: Blob of files to lint
    required: false
    default: '.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo-token }}
    - ${{ inputs.path }}
    - ${{ inputs.files }}
branding: 
  icon: circle
  color: purple